### ISSUE TITLE
--proxy Setting gives [!] incorrect proxy type

### ISSUE THREAD

**Issue by HamzaMehmood** [trimstray/multitor#11]
If i run multitor with: multitor --init 2 -u debian-tor --socks-port 9000 --control-port 9900 --proxy http
I get: [!] incorrect proxy type

**Comment by trimstray** [comment]
Pull to new version:

```bash
git pull origin master && git fetch --all && git fetch --prune --tags
```

In [v1.3.0](https://github.com/trimstray/multitor/tree/v1.3.0) `--proxy` param has these values:

```bash
--proxy <proxy_type>          set socks or http (polipo, privoxy, hpts) proxy server
```

And if you want to use **HAProxy** as a frontend (`--haproxy` param):

```bash
multitor --init 2 -u debian-tor --socks-port 9000 --control-port 9900 --proxy polipo --haproxy
```
