### ISSUE TITLE
privoxy not run in arch linux with multitor

### ISSUE THREAD

**Issue by Odyssey2247** [trimstray/multitor#15]
I have the problem that privoxy does not work command:

    multitor --init 2 -u misec --socks-port 9000 --control-port 9900 --proxy privoxy

the working processes:

    [ root ]# netstat -tapn | grep LISTEN | grep "tor\|haproxy\|polipo\|privoxy\|node"
    tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      2237/tor            
    tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      2296/tor            
    tcp        0      0 127.0.0.1:9900          0.0.0.0:*               LISTEN      2237/tor            
    tcp        0      0 127.0.0.1:9901          0.0.0.0:*               LISTEN      2296/tor            
    tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      14827/tor           
    tcp        0      0 127.0.0.1:16379         0.0.0.0:*               LISTEN      2395/haproxy        
    tcp        0      0 127.0.0.1:16380         0.0.0.0:*               LISTEN      2395/haproxy    

privoxy only works if I run it manually with the configuration file of the /multitor/etc directory
     
    /usr/bin/privoxy --no-daemon privoxy.cfg 

what is happening?

**Comment by trimstray** [comment]
```
» multitor --init 5 --user debian-tor --socks-port 9500 --control-port 9600 --proxy privoxy

     Set processes: 5
           Created: 5
       Not created: 0
  Control password: jKTfYzvuV98alvIIj5

       Proxy state: running (privoxy » haproxy » socks)

» netstat -tapn | grep LISTEN                                    
tcp        0      0 127.0.0.1:16379         0.0.0.0:*               LISTEN      30452/haproxy   
tcp        0      0 127.0.0.1:16380         0.0.0.0:*               LISTEN      30452/haproxy   
tcp        0      0 127.0.0.1:9500          0.0.0.0:*               LISTEN      30078/tor       
tcp        0      0 127.0.0.1:9501          0.0.0.0:*               LISTEN      30137/tor       
tcp        0      0 127.0.0.1:9502          0.0.0.0:*               LISTEN      30196/tor       
tcp        0      0 127.0.0.1:9503          0.0.0.0:*               LISTEN      30255/tor       
tcp        0      0 127.0.0.1:9504          0.0.0.0:*               LISTEN      30314/tor       
tcp        0      0 127.0.0.1:9600          0.0.0.0:*               LISTEN      30078/tor       
tcp        0      0 127.0.0.1:9601          0.0.0.0:*               LISTEN      30137/tor       
tcp        0      0 127.0.0.1:9602          0.0.0.0:*               LISTEN      30196/tor       
tcp        0      0 127.0.0.1:9603          0.0.0.0:*               LISTEN      30255/tor       
tcp        0      0 127.0.0.1:9604          0.0.0.0:*               LISTEN      30314/tor       
```
