### ISSUE TITLE
Getting this error...Please help

### ISSUE THREAD

**Issue by djtroby** [trimstray/multitor#18]
not found in PATH: haproxy polipo privoxy hpts
the above error i get while executing the multitor....FYI haproxy, polipo, privoxy and hpts is installed in Kali ....version
Linux kali 4.16.0-kali2-amd64 #1 SMP Debian 4.16.16-2kali1 (2018-06-25) x86_64 GNU/Linux

**Comment by trimstray** [comment]
Multitor uses this `PATH` variable:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

I think you should create symlinks for all external tools.

**Comment by UBISOFT-1** [comment]
That's not the problem @trimstray , well in one case it could be, but as this is a very common issue 
Just writing this to help some one who already has all the symlinks in place :)
`sudo apt-get install haproxy`
`sudo apt-get install polipo`
`sudo apt-get install privoxy`
`sudo apt-get install hpts`
Hope this Helps some one else and these should be auto installed in `setup.sh` @trimstray 
:)
