### ISSUE TITLE
bad multitor directory owner

### ISSUE THREAD

**Issue by httpbob** [trimstray/multitor#19]
Hello,

I get the following error after trying to launch those commands:
```
git clone https://github.com/trimstray/multitor
cd multitor
./setup.sh install
multitor --init 2 --user debian-tor --socks-port 9000 --control-port 9900 --proxy privoxy --haproxy
```

> [!] bad multitor directory owner

I'm working on clean version of debian 9.

Can you please help me trying to understand the causes of this error ?

Thanks a lot for your time and help

**Comment by Skarlett** [comment]
Related to #3
