### ISSUE TITLE
Proxy state disable (only tor)

### ISSUE THREAD

**Issue by adon90** [trimstray/multitor#4]
I have run:

service haproxy start
service tor start
service polipo start

I have tried creating the user debian-tor I have run it with the services stopped, I don't know why I keep getting: `Proxy state disable (only tor)` thanks

**Comment by trimstray** [comment]
Hi!

First of all: paste the log files:
- `log/multitor.<date>.log`
- `stdout.log`

Multitor automatically starts all required services.

**Comment by someusername123** [comment]
I had this same issue (which was a id10t error) if you forget to use --proxy socks|http it will throw this error. I would recommend making the --proxy a required field or it will throw an error. See below

(without - throws proxy state disabled )
multitor --init 2 --user debian-tor --socks-port 9000 --control-port 9900 --debug
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() starting debug mode
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() init_state: '1'
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() init_number: '2'
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() user_state: '1'
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() user_name: 'debian-tor'
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() socks_port_state: '1'
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() socks_port_number: '9000'
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() control_port_state: '1'
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() control_port_number: '9900'
20/06/18 03:35:46 PM  multitor:  [WARN] __main__() not found tor processes: 
20/06/18 03:35:46 PM  multitor:  [INFO] __main__() socks_port_number: '9000', control_port_number: '9900'
20/06/18 03:35:46 PM  multitor:  [INFO] CreateTorDirectory() created tor process directory: /var/lib/multitor/9000
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorDirectory() changed owner properly to: 'debian-tor'
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorProcess() saved HashedControlPassword correctly
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorProcess() change permission and owner correctly
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorProcess() create process: '9000.pid'
20/06/18 03:35:47 PM  multitor:  [INFO] __main__() socks_port_number: '9001', control_port_number: '9901'
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorDirectory() created tor process directory: /var/lib/multitor/9001
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorDirectory() changed owner properly to: 'debian-tor'
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorProcess() saved HashedControlPassword correctly
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorProcess() change permission and owner correctly
20/06/18 03:35:47 PM  multitor:  [INFO] CreateTorProcess() create process: '9001.pid'
20/06/18 03:35:47 PM  multitor:  [WARN] CheckProxyProcess() not found proxy processes
20/06/18 03:35:47 PM  multitor:  [WARN] CheckProxyProcess() not found proxy processes
20/06/18 03:35:47 PM  multitor:  [WARN] CheckProxyProcess() not found proxy processes
20/06/18 03:35:47 PM  multitor:  [WARN] CheckProxyProcess() not found proxy processes

     Set processes: 2
           Created: 2
       Not created: 0
  Control password: notmypassword

       Proxy state: disable (only tor)

20/06/18 03:35:47 PM  multitor:  [EXIT] _get_trap_SIG > EXIT (0)

(with --proxy socks)
multitor --init 2 --user debian-tor --socks-port 9000 --control-port 9900 --proxy socks --debug
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() starting debug mode
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() correct proxy type: 'socks'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() init_state: '1'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() init_number: '2'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() user_state: '1'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() user_name: 'debian-tor'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() socks_port_state: '1'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() socks_port_number: '9000'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() control_port_state: '1'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() control_port_number: '9900'
20/06/18 03:36:55 PM  multitor:  [INFO] DestroyProcess() killed tor process: '15732'
20/06/18 03:36:55 PM  multitor:  [INFO] DestroyProcess() killed tor process: '15661'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() socks_port_number: '9000', control_port_number: '9900'
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorDirectory() created tor process directory: /var/lib/multitor/9000
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorDirectory() changed owner properly to: 'debian-tor'
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorProcess() saved HashedControlPassword correctly
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorProcess() change permission and owner correctly
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorProcess() create process: '9000.pid'
20/06/18 03:36:55 PM  multitor:  [INFO] __main__() socks_port_number: '9001', control_port_number: '9901'
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorDirectory() created tor process directory: /var/lib/multitor/9001
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorDirectory() changed owner properly to: 'debian-tor'
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorProcess() saved HashedControlPassword correctly
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorProcess() change permission and owner correctly
20/06/18 03:36:55 PM  multitor:  [INFO] CreateTorProcess() create process: '9001.pid'
20/06/18 03:36:55 PM  multitor:  [WARN] CheckProxyProcess() not found proxy processes
20/06/18 03:36:55 PM  multitor:  [WARN] CheckProxyProcess() not found proxy processes
20/06/18 03:36:55 PM  multitor:  [INFO] CreateProxyProcess() added backend port for haproxy: '9000'
20/06/18 03:36:55 PM  multitor:  [INFO] CreateProxyProcess() added backend port for haproxy: '9001'
20/06/18 03:36:55 PM  multitor:  [INFO] CreateProxyProcess() init proxy process with '**removed**' config file
20/06/18 03:36:55 PM  multitor:  [INFO] CheckProxyProcess() added proxy process with 'haproxy:16112' pid
20/06/18 03:36:55 PM  multitor:  [WARN] CheckProxyProcess() not found proxy processes

     Set processes: 2
           Created: 2
       Not created: 0
  Control password: notmyrealpass

       Proxy state: running (socks proxy)

20/06/18 03:36:55 PM  multitor:  [EXIT] _get_trap_SIG > EXIT (0)

**Comment by trimstray** [comment]
If you init multitor without `--proxy <proxy_type>` the following processes will be started:

```bash
debian-+ 17986 30.7  0.1  70824 29156 ?        S    08:54   0:01 tor -f /var/lib/multitor/9000/9000.torrc --RunAsDaemon 1 --CookieAuthentication 0 --SocksPort 9000 --ControlPort 9900 --PidFile /var/lib/multitor/9000/9000.pid --DataDirectory /var/lib/multitor/9000
debian-+ 18046 27.0  0.1  74012 30664 ?        S    08:54   0:01 tor -f /var/lib/multitor/9001/9001.torrc --RunAsDaemon 1 --CookieAuthentication 0 --SocksPort 9001 --ControlPort 9901 --PidFile /var/lib/multitor/9001/9001.pid --DataDirectory /var/lib/multitor/9001
debian-+ 18105 36.0  0.1  78928 35192 ?        R    08:54   0:01 tor -f /var/lib/multitor/9002/9002.torrc --RunAsDaemon 1 --CookieAuthentication 0 --SocksPort 9002 --ControlPort 9902 --PidFile /var/lib/multitor/9002/9002.pid --DataDirectory /var/lib/multitor/9002
debian-+ 18164 24.0  0.1  69316 27336 ?        S    08:54   0:00 tor -f /var/lib/multitor/9003/9003.torrc --RunAsDaemon 1 --CookieAuthentication 0 --SocksPort 9003 --ControlPort 9903 --PidFile /var/lib/multitor/9003/9003.pid --DataDirectory /var/lib/multitor/9003
debian-+ 18227 15.2  0.1  63764 21776 ?        S    08:54   0:00 tor -f /var/lib/multitor/9004/9004.torrc --RunAsDaemon 1 --CookieAuthentication 0 --SocksPort 9004 --ControlPort 9904 --PidFile /var/lib/multitor/9004/9004.pid --DataDirectory /var/lib/multitor/9004
```

It's normal situation because no proxy server initialization parameter was specified for tor processes. Running a multitor in this mode is useful for running many processes and using them by other programs: e-mail clients, web browsers, messengers.
