### ISSUE TITLE
Stop multitor processes: kill param

### ISSUE THREAD

**Issue by puzanov** [trimstray/multitor#6]
Hey

Thanks for the tool. Nice to have one. 

How to gracefully stop multitor? Cannot find the command in help

**Comment by trimstray** [comment]
Hi!

There is no such option but you can deal with it in a simple way:

```bash
# pkill -f multitor
# netstat -tapn | grep LISTEN | grep "tor\|haproxy\|polipo"
tcp        0      0 127.0.0.1:8123          0.0.0.0:*               LISTEN      1137/polipo
```

However, I will add this in the next version.

Thx!

**Comment by puzanov** [comment]
thanks
