### ISSUE TITLE
Create man page to /usr/local/man/man8

### ISSUE THREAD

**Issue by adammokhlisse** [trimstray/multitor#7]
i try install your script but when i run
./setup.sh install 
i get this error .
Create man page to /usr/local/man/man8

plus what command needed to make my all internet in vps use your script exactly "http proxy"
? please help ASAP.

**Comment by trimstray** [comment]
1) It's not a bug - `setup.sh` installs the script and manual page in the appropriate location. After installation, execute the `multitor` from the console.

2) Look at wiki page: **[Multitor - HTTP Proxy](https://github.com/trimstray/multitor/wiki/Manual#http-proxy)**.
